version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    container_name: expenses-manager-db
    volumes:
      - expenses-manager-db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  expenses-manager-db-data:
    driver: local
